/**
 * js/pages/mcp.js
 * Scripted demo for the MCP page chatbox.
 * Demonstrates Bob querying Instana for a full observability report on
 * visang_edu2, writing a Markdown file, then surfacing it in the explorer.
 *
 * Requires: css/pages.css, js/chat-helpers.js
 */
(function () {

  /* ── Rich script format ─────────────────────────────────────────────────
   * Each step has:
   *   user  : string  — the user message
   *   bob   : Array   — sequence of segments rendered in order:
   *     { type: 'text',    text: string }         plain prose (typewritten)
   *     { type: 'mcp',     label, tools, secs }   collapsed tool-call pill
   *     { type: 'writing' }                        animated "Writing file" bar
   *     { type: 'wrote',   filename: string }      "Wrote file" row + explorer
   *     { type: 'rich',    html: string }          rendered HTML block
   *     { type: 'footer' }                         "1 file changed" bar
   * ─────────────────────────────────────────────────────────────────────── */
  const REPORT_MD = `# Instana Observability Report — Visang_edu2

> **Generated:** 2026-08-25
> **Application ID:** \`iXrWLPgCQHeOILPL1VsmoQ\`
> **Observation Window:** Last 24 hours
> **Instana Namespace Filter:** \`kubernetes.namespace.name = robot-shop\`

---

## 1. Application Overview

| Property | Value |
|---|---|
| **Name** | Visang_edu2 |
| **ID** | \`iXrWLPgCQHeOILPL1VsmoQ\` |
| **Boundary Scope** | ALL |
| **Namespace Filter** | \`kubernetes.namespace.name = robot-shop\` (DESTINATION) |
| **Access** | READ_WRITE (Global) |

---

## 2. Service Health Summary (Last 24 Hours)

### 2.1 Services with Errors ⚠️

| Service | Total Calls | Error Rate | Mean Latency | P99 Latency |
|---|---|---|---|---|
| \`recommendation-svc\` | 2,966 | **100%** | 2.13 ms | 3 ms |
| \`nginx-web\` | 703,150 | **0.60%** | 71.59 ms | 2,006 ms |
| \`catalogue-demo\` | 194,573 | **2.05%** | 47.82 ms | 2,006 ms |
| \`discount-svc\` | 132,216 | **2.94%** | 64.19 ms | 2,006 ms |
| \`MySQL@3306 on workload-driver-managed-demo\` | 112,922 | **3.44%** | 69.56 ms | 2,006 ms |
| \`demo-us-eks-robot-shop-ratings\` | 60,066 | **3.30%** | 82.71 ms | 2,006 ms |
| \`payment\` | 115,563 | **0.02%** | 320.22 ms | 2,373 ms |

### 2.2 Services Operating Normally ✅

| Service | Total Calls | Mean Latency | P99 Latency |
|---|---|---|---|
| \`mycluster-jp-tok-2-bx2.2x8-robot-shop-mysql\` | 908,628 | 1.50 ms | 18 ms |
| \`mycluster-jp-tok-2-bx2.2x8-robot-shop-catalogue\` | 476,901 | 6.59 ms | 57 ms |
| \`mycluster-jp-tok-2-bx2.2x8-robot-shop-mongodb\` | 476,901 | 4.08 ms | 40 ms |
| \`demo-us-eks-robot-shop-redis\` | 217,717 | 0.44 ms | 1 ms |

---

## 3. Critical Findings

### 🔴 100% Error Rate — recommendation-svc
All 2,966 calls failed. P99 = 3 ms (fast-fail). Likely connection refused or immediate HTTP 5xx.

### 🔴 MySQL Timeout Cascade
\`MySQL@3306 on workload-driver-managed-demo\` — 3.44% errors, P99 exactly **2,006 ms**.
This timeout value propagates to discount-svc, ratings, catalogue-demo, and nginx-web.

### 🟠 Payment Service Latency
Mean 320 ms · P99 2,373 ms — highest among app-layer services.

---

## 4. Root Cause Hypothesis

\`\`\`
MySQL@3306 (workload-driver-managed-demo)
    ├── High error rate (3.44%) + P99 2,006ms timeout
    └── Cascades to:
         ├── discount-svc  (2.94% errors, P99 2,006ms)
         ├── ratings       (3.30% errors, P99 2,006ms)
         ├── catalogue-demo (2.05% errors, P99 2,006ms)
         └── nginx-web     (0.60% errors, P99 2,006ms)
\`\`\`

---

## 5. Recommendations

1. **Investigate recommendation-svc** — 100% error rate, immediate action needed.
2. **Diagnose MySQL@3306** — slow queries, connection pool, disk I/O.
3. **Scale cluster capacity** — 5 nodes reporting Insufficient CPU/memory.
4. **Set timeout < 2,000 ms** on upstream callers to fail fast.
5. **Circuit breakers** — nginx-web → discount/ratings/catalogue.

---

*Report generated by IBM Bob using IBM Instana MCP integration.*`;

  const SCRIPT = [
    {
      user: 'bob, in my instana instance, check visang_edu2, make a comprehensive report in an md after',
      bob: [
        { type: 'text',
          text: "I'll start by investigating your Instana instance to gather comprehensive data about visang_edu2. Let me pull information from multiple sources in parallel." },
        { type: 'mcp',  label: 'Called MCP', tools: 2, secs: 8 },
        { type: 'text',
          text: "Good — application config found. Now let me pull application metrics, services, endpoints, and alert configurations for visang_edu2 in parallel." },
        { type: 'mcp',  label: 'Called MCP', tools: 7, secs: 12 },
        { type: 'text',  text: "Now I have all the data I need. Let me write the comprehensive Markdown report." },
        { type: 'writing' },
        { type: 'wrote', filename: 'visang_edu2_instana_report.md' },
        { type: 'rich', html: `
<div class="bcpr-summary">
  <p class="bcpr-lead">The report has been written to <code class="bcp-inline-code">visang_edu2_instana_report.md</code>. Here's a summary of what was found:</p>
  <hr class="bcpr-divider" />
  <h3 class="bcpr-h3">Key Findings for Visang_edu2</h3>
  <p class="bcpr-p"><strong class="bcpr-strong">App config:</strong> Scoped to <code class="bcp-inline-code">kubernetes.namespace.name = robot-shop</code>, boundary scope ALL, 33 services tracked.</p>
  <p class="bcpr-section-label">🔴 Critical Issues</p>
  <table class="bcpr-table">
    <thead><tr><th>Finding</th><th>Detail</th></tr></thead>
    <tbody>
      <tr>
        <td><code class="bcp-inline-code">recommendation-svc</code> — <strong class="bcpr-strong">100% error rate</strong></td>
        <td>All 2,966 calls failed; fast-fail behaviour (P99 3 ms) suggests connection refused or immediate HTTP 5xx</td>
      </tr>
      <tr>
        <td><strong class="bcpr-strong">MySQL timeout cascade</strong></td>
        <td><code class="bcp-inline-code">MySQL@3306 on workload-driver-managed-demo</code> has 3.44% errors and P99 exactly 2,006 ms — this exact timeout value propagates to discount-svc, ratings, catalogue-demo, and nginx-web</td>
      </tr>
      <tr>
        <td><strong class="bcpr-strong">Node resource exhaustion</strong></td>
        <td>Cluster nodes have been reporting Insufficient CPU and Insufficient memory for 4+ days, directly causing pod scheduling failures</td>
      </tr>
    </tbody>
  </table>
  <p class="bcpr-section-label">🟠 High Concerns</p>
  <ul class="bcpr-list">
    <li>payment service — mean latency 320 ms, P99 2,373 ms (highest among app-layer services)</li>
    <li>demo-us-eks-robot-shop-user — P99 2,187 ms</li>
    <li>Multiple recurring incidents in the past 24h around ratings, MySQL, catalogue-demo, and nginx-web</li>
  </ul>
  <p class="bcpr-section-label">✅ Healthy High-Volume Services</p>
  <p class="bcpr-p">mycluster-jp-tok-2-bx2.2x8-* cluster's services (MySQL, catalogue, MongoDB, cart, user) are all operating with zero errors and sub-20 ms P99 latency.</p>
</div>` },
        { type: 'footer' }
      ]
    }
  ];

  /* ── DOM refs ── */
  const fab      = document.getElementById('plan-bob-fab');
  const fabWrap  = document.getElementById('plan-bob-fab-wrap');
  const landing  = document.getElementById('mcp-landing');
  const chat     = document.getElementById('plan-chat-view');
  const closeBtn = document.getElementById('bcp-close-btn');

  if (!fab || !landing || !chat) return;

  /* ── FAB → chatbox transition ──────────────────────────────────────────
     Guard with a flag so clicking the FAB (which also bubbles to fabWrap)
     doesn't call openChat twice and attach duplicate send-button listeners. */
  let chatInitialised = false;

  function openChat() {
    if (chatInitialised) return;
    chatInitialised = true;
    landing.classList.add('plan-landing--out');
    setTimeout(() => {
      landing.style.display = 'none';
      fabWrap.style.display = 'none';
      chat.classList.remove('hidden');
      chat.classList.add('plan-chat-view--in');
      initMcpChat();
    }, 320);
  }

  fab.addEventListener('click', openChat);
  fabWrap.addEventListener('click', openChat);

  if (closeBtn) {
    closeBtn.addEventListener('click', () => {
      chat.classList.add('hidden');
      landing.style.display = '';
      landing.classList.remove('plan-landing--out');
      fabWrap.style.display = '';
      // Allow re-init on next open
      chatInitialised = false;
    });
  }

  /* ── Settings panel + resize elements ── */
  const settingsCol   = document.getElementById('bob-settings-col');
  const settingsPanel = document.getElementById('bob-settings');
  const settingsBtn   = document.getElementById('bob-settings-btn');
  const settingsClose = document.getElementById('bob-settings-close');
  const resizeHandle  = document.getElementById('bcp-resize-handle');

  /* ── Settings resize handle ── */
  if (resizeHandle) {
    let dragging = false;
    let startX   = 0;
    let startW   = 0;

    resizeHandle.addEventListener('mousedown', e => {
      if (!settingsCol || settingsCol.classList.contains('hidden')) return;
      dragging = true;
      startX   = e.clientX;
      startW   = settingsCol.getBoundingClientRect().width;
      resizeHandle.classList.add('dragging');
      document.body.style.cursor     = 'col-resize';
      document.body.style.userSelect = 'none';
      e.preventDefault();
    });

    document.addEventListener('mousemove', e => {
      if (!dragging) return;
      const delta = e.clientX - startX;
      const newW  = Math.min(Math.max(startW + delta, 280), 760);
      settingsCol.style.width = newW + 'px';
    });

    document.addEventListener('mouseup', () => {
      if (!dragging) return;
      dragging = false;
      resizeHandle.classList.remove('dragging');
      document.body.style.cursor     = '';
      document.body.style.userSelect = '';
    });
  }

  if (settingsBtn && settingsCol) {
    settingsBtn.addEventListener('click', () => {
      const isHidden = settingsCol.classList.toggle('hidden');
      if (!isHidden) {
        settingsPanel.classList.remove('hidden');
        showTab('settings');
      }
    });
  }
  if (settingsClose && settingsCol) {
    settingsClose.addEventListener('click', () => {
      settingsCol.classList.add('hidden');
    });
  }

  /* ── Add MCP Server modal ── */
  const addBtn      = document.querySelector('.bob-settings-icon-btn[title="Add"]');
  const modal       = document.getElementById('bob-mcp-modal');
  const modalClose  = document.getElementById('bob-mcp-modal-close');
  const cancelBtn   = document.getElementById('bob-mcp-cancel');
  const confirmBtn  = document.getElementById('bob-mcp-confirm');
  const scopeItems  = modal ? modal.querySelectorAll('.bob-mcp-scope-item') : [];

  const jsonView      = document.getElementById('bob-json-view');
  const settingsBody  = settingsPanel ? settingsPanel.querySelector('.bob-settings-body') : null;
  const tabSettings   = document.getElementById('bob-tab-settings');
  const tabJson       = document.getElementById('bob-tab-json');
  const tabJsonClose  = document.getElementById('bob-tab-json-close');

  function showTab(tab) {
    if (tab === 'json') {
      if (settingsBody) settingsBody.classList.add('hidden');
      if (jsonView) jsonView.classList.remove('hidden');
      if (tabSettings) tabSettings.classList.remove('active');
      if (tabJson) { tabJson.classList.remove('hidden'); tabJson.classList.add('active'); }
    } else {
      if (jsonView) jsonView.classList.add('hidden');
      if (settingsBody) settingsBody.classList.remove('hidden');
      if (tabJson) tabJson.classList.remove('active');
      if (tabSettings) tabSettings.classList.add('active');
    }
  }

  if (tabSettings) tabSettings.addEventListener('click', () => showTab('settings'));
  if (tabJsonClose) tabJsonClose.addEventListener('click', e => {
    e.stopPropagation();
    if (tabJson) tabJson.classList.add('hidden');
    showTab('settings');
  });

  function openModal()  { if (modal) modal.classList.remove('hidden'); }
  function closeModal() { if (modal) { modal.classList.add('hidden'); clearScope(); } }
  function clearScope() {
    scopeItems.forEach(item => item.classList.remove('selected'));
    if (confirmBtn) confirmBtn.disabled = true;
  }

  if (addBtn)     addBtn.addEventListener('click', openModal);
  if (modalClose) modalClose.addEventListener('click', closeModal);
  if (cancelBtn)  cancelBtn.addEventListener('click', closeModal);
  if (confirmBtn) confirmBtn.addEventListener('click', () => { closeModal(); showTab('json'); });

  scopeItems.forEach(item => {
    item.addEventListener('click', () => {
      scopeItems.forEach(s => s.classList.remove('selected'));
      item.classList.add('selected');
      if (confirmBtn) confirmBtn.disabled = false;
    });
  });

  if (modal) {
    modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });
  }

  /* ── MD viewer panel ────────────────────────────────────────────────────
     Opens when the user clicks "Wrote file" or a .md file in the explorer.
     Renders the raw Markdown as styled HTML. ─────────────────────────── */
  const mdPanel      = document.getElementById('bcp-md-panel');
  const mdClose      = document.getElementById('bcp-md-close');
  const mdBody       = document.getElementById('bcp-md-body');
  const mdTabName    = document.getElementById('bcp-md-tab-name');
  const mdBcName     = document.getElementById('bcp-md-bc-name');
  const mdResizeHnd  = document.getElementById('bcp-md-resize-handle');

  function openMdPanel(filename, markdown) {
    if (!mdPanel) return;
    if (mdTabName) mdTabName.textContent = filename;
    if (mdBcName)  mdBcName.textContent  = filename;
    if (mdBody)    mdBody.innerHTML = renderMarkdown(markdown);
    mdPanel.classList.remove('hidden');
  }

  if (mdClose) {
    mdClose.addEventListener('click', () => {
      if (mdPanel) mdPanel.classList.add('hidden');
    });
  }

  /* MD panel resize */
  if (mdResizeHnd && mdPanel) {
    let mDragging = false;
    let mStartX   = 0;
    let mStartW   = 0;

    mdResizeHnd.addEventListener('mousedown', e => {
      if (mdPanel.classList.contains('hidden')) return;
      mDragging = true;
      mStartX   = e.clientX;
      mStartW   = mdPanel.getBoundingClientRect().width;
      mdResizeHnd.classList.add('dragging');
      document.body.style.cursor     = 'col-resize';
      document.body.style.userSelect = 'none';
      e.preventDefault();
    });

    document.addEventListener('mousemove', e => {
      if (!mDragging) return;
      const delta = e.clientX - mStartX;
      const newW  = Math.min(Math.max(mStartW + delta, 240), 700);
      mdPanel.style.width = newW + 'px';
    });

    document.addEventListener('mouseup', () => {
      if (!mDragging) return;
      mDragging = false;
      mdResizeHnd.classList.remove('dragging');
      document.body.style.cursor     = '';
      document.body.style.userSelect = '';
    });
  }

  /* ── Minimal Markdown → HTML renderer ──────────────────────────────────
     Handles: headings, bold, inline code, fenced code, tables, lists, hr,
     blockquotes, and paragraphs. ──────────────────────────────────────── */
  function renderMarkdown(md) {
    const lines  = md.split('\n');
    const out    = [];
    let i        = 0;

    function escHtml(s) {
      return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    }

    function inlineRender(s) {
      // Bold **text**
      s = s.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      // Inline code `code`
      s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
      return s;
    }

    while (i < lines.length) {
      const line = lines[i];

      // Fenced code block
      if (line.startsWith('```')) {
        const lang = line.slice(3).trim();
        let code = '';
        i++;
        while (i < lines.length && !lines[i].startsWith('```')) {
          code += escHtml(lines[i]) + '\n';
          i++;
        }
        out.push(`<pre><code${lang ? ` class="lang-${lang}"` : ''}>${code}</code></pre>`);
        i++;
        continue;
      }

      // Headings
      const hm = line.match(/^(#{1,4})\s+(.*)/);
      if (hm) {
        const lvl = hm[1].length;
        out.push(`<h${lvl}>${inlineRender(escHtml(hm[2]))}</h${lvl}>`);
        i++; continue;
      }

      // HR
      if (/^---+$/.test(line.trim())) {
        out.push('<hr>');
        i++; continue;
      }

      // Blockquote
      if (line.startsWith('> ')) {
        out.push(`<blockquote>${inlineRender(escHtml(line.slice(2)))}</blockquote>`);
        i++; continue;
      }

      // Table — collect all consecutive table lines
      if (line.startsWith('|')) {
        const tableLines = [];
        while (i < lines.length && lines[i].startsWith('|')) {
          tableLines.push(lines[i]);
          i++;
        }
        // First row = header, second = separator (skip), rest = body
        const [head, , ...body] = tableLines;
        const thCells = head.split('|').slice(1,-1).map(c =>
          `<th>${inlineRender(escHtml(c.trim()))}</th>`).join('');
        const rows = body.map(r =>
          '<tr>' + r.split('|').slice(1,-1).map(c =>
            `<td>${inlineRender(escHtml(c.trim()))}</td>`).join('') + '</tr>').join('');
        out.push(`<table><thead><tr>${thCells}</tr></thead><tbody>${rows}</tbody></table>`);
        continue;
      }

      // Unordered list
      if (/^[-*]\s/.test(line)) {
        const items = [];
        while (i < lines.length && /^[-*]\s/.test(lines[i])) {
          items.push(`<li>${inlineRender(escHtml(lines[i].slice(2)))}</li>`);
          i++;
        }
        out.push(`<ul>${items.join('')}</ul>`);
        continue;
      }

      // Blank line
      if (line.trim() === '') {
        i++; continue;
      }

      // Paragraph
      out.push(`<p>${inlineRender(escHtml(line))}</p>`);
      i++;
    }

    return out.join('\n');
  }

  /* ══════════════════════════════════════════════════════════════
     Rich MCP chat renderer
     ══════════════════════════════════════════════════════════════ */
  function initMcpChat() {
    const body     = document.getElementById('bcp-body');
    const welcome  = document.getElementById('bcp-welcome');
    const msgs     = document.getElementById('bcp-messages');
    const inputEl  = document.getElementById('bcp-scripted-input');
    const inputBox = document.getElementById('bcp-input-box');
    const sendBtn  = document.getElementById('bcp-send');
    const expTree  = document.querySelector('.bcp-exp-tree');

    let step = 0;
    let busy = false;

    function scrollToBottom() {
      body.scrollTo({ top: body.scrollHeight, behavior: 'smooth' });
    }

    function activateChat() {
      if (!msgs.classList.contains('active')) {
        welcome.classList.add('hidden');
        msgs.classList.add('active');
      }
    }

    function addUserMsg(text) {
      const row = document.createElement('div');
      row.className = 'bcp-msg-user';
      const b = document.createElement('div');
      b.className = 'bcp-user-bubble';
      b.textContent = text;
      row.appendChild(b);
      msgs.appendChild(row);
      scrollToBottom();
    }

    function addBobRow() {
      const row = document.createElement('div');
      row.className = 'bcp-msg-bob';
      const av = document.createElement('img');
      av.src = 'asset/bob.png'; av.alt = 'Bob'; av.className = 'bcp-bob-avatar';
      row.appendChild(av);
      const c = document.createElement('div');
      c.className = 'bcp-bob-content';
      const n = document.createElement('div');
      n.className = 'bcp-bob-name'; n.textContent = 'IBM Bob';
      c.appendChild(n);
      row.appendChild(c);
      msgs.appendChild(row);
      return c;
    }

    function typewrite(el, text, speed = 9) {
      return new Promise(resolve => {
        let i = 0;
        function tick() {
          if (i >= text.length) { resolve(); return; }
          el.textContent += text[i++];
          scrollToBottom();
          setTimeout(tick, speed);
        }
        tick();
      });
    }

    function appendMcpBlock(contentDiv, label, tools, secs) {
      const el = document.createElement('div');
      el.className = 'bcpr-mcp-call';
      el.innerHTML =
        `<span class="bcpr-mcp-icon">&#10025;</span>` +
        `<span class="bcpr-mcp-label">${label}</span>` +
        `<span class="bcpr-mcp-meta">${tools} tool${tools !== 1 ? 's' : ''} · ${secs}s</span>` +
        `<span class="bcpr-mcp-arrow">›</span>`;
      contentDiv.appendChild(el);
      scrollToBottom();
    }

    function appendWritingBar(contentDiv) {
      const el = document.createElement('div');
      el.className = 'bcpr-working-bar';
      el.innerHTML =
        `<svg class="bcp-hammer-icon" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">` +
        `<path d="M9 2L14 7L7 14L2 9L9 2Z" stroke="#858585" stroke-width="1.4" stroke-linejoin="round"/>` +
        `<path d="M12 1L15 4" stroke="#858585" stroke-width="1.4" stroke-linecap="round"/>` +
        `</svg>` +
        `<span class="bcp-working-text">Writing file</span>`;
      contentDiv.appendChild(el);
      scrollToBottom();
      return el;
    }

    function appendWroteFile(contentDiv, filename) {
      const el = document.createElement('div');
      el.className = 'bcp-wrote-file';
      el.style.cursor = 'pointer';
      el.title = 'Open ' + filename;
      el.innerHTML =
        `<span class="bcp-wrote-file-icon">&#9998;</span>` +
        `<span class="bcp-wrote-file-name">${filename}</span>` +
        `<span class="bcp-wrote-file-arrow">›</span>`;
      // Clicking the "Wrote file" row opens the MD panel
      el.addEventListener('click', () => openMdPanel(filename, REPORT_MD));
      contentDiv.appendChild(el);
      addExplorerFile(filename);
      scrollToBottom();
    }

    function appendRich(contentDiv, html) {
      const el = document.createElement('div');
      el.className = 'bcpr-rich';
      el.innerHTML = html;
      contentDiv.appendChild(el);
      scrollToBottom();
    }

    function appendFooter(contentDiv) {
      const el = document.createElement('div');
      el.className = 'bcpr-file-footer';
      el.innerHTML =
        `<span class="bcpr-file-footer-icon">&#128194;</span>` +
        `<span class="bcpr-file-footer-count">1 file changed</span>` +
        `<span class="bcpr-file-footer-sep"></span>` +
        `<button class="bcpr-file-footer-btn">Undo all</button>` +
        `<button class="bcpr-file-footer-btn">Show all</button>` +
        `<span class="bcpr-file-footer-chevron">&#8964;</span>`;
      contentDiv.appendChild(el);
      scrollToBottom();
    }

    function addExplorerFile(filename) {
      if (!expTree) return;
      const file = document.createElement('div');
      file.className = 'bcp-exp-file active';
      file.style.cursor = 'pointer';
      file.innerHTML =
        `<span class="bcp-exp-file-icon">&#128196;</span>` +
        `<span class="bcp-exp-file-name">${filename}</span>`;
      // Clicking the explorer file opens the MD panel
      file.addEventListener('click', () => openMdPanel(filename, REPORT_MD));
      expTree.appendChild(file);
      setTimeout(() => file.classList.remove('active'), 3000);
    }

    async function renderSegments(segments) {
      let contentDiv = null;

      for (const seg of segments) {
        if (seg.type === 'text') {
          contentDiv = addBobRow();
          const textEl = document.createElement('div');
          textEl.className = 'bcp-bob-text';
          contentDiv.appendChild(textEl);
          await typewrite(textEl, seg.text);
          await new Promise(r => setTimeout(r, 300));
        }
        else if (seg.type === 'mcp') {
          if (!contentDiv) contentDiv = addBobRow();
          await new Promise(r => setTimeout(r, 400));
          appendMcpBlock(contentDiv, seg.label, seg.tools, seg.secs);
          await new Promise(r => setTimeout(r, seg.secs * 80));
        }
        else if (seg.type === 'writing') {
          if (!contentDiv) contentDiv = addBobRow();
          const bar = appendWritingBar(contentDiv);
          await new Promise(r => setTimeout(r, 1400));
          bar.remove();
        }
        else if (seg.type === 'wrote') {
          if (!contentDiv) contentDiv = addBobRow();
          appendWroteFile(contentDiv, seg.filename);
          await new Promise(r => setTimeout(r, 300));
        }
        else if (seg.type === 'rich') {
          if (!contentDiv) contentDiv = addBobRow();
          appendRich(contentDiv, seg.html);
          await new Promise(r => setTimeout(r, 200));
        }
        else if (seg.type === 'footer') {
          if (!contentDiv) contentDiv = addBobRow();
          appendFooter(contentDiv);
        }
      }
    }

    function updateUI() {
      if (step < SCRIPT.length) {
        inputEl.textContent = SCRIPT[step].user;
        inputEl.classList.add('ready');
        inputBox.classList.add('active');
        sendBtn.disabled = false;
        sendBtn.classList.add('pulse');
      } else {
        inputEl.textContent = 'end of MCP demo';
        inputEl.classList.remove('ready');
        inputBox.classList.remove('active');
        sendBtn.disabled = true;
        sendBtn.classList.remove('pulse');

        const wrap = document.createElement('div');
        wrap.className = 'bcp-done-wrap';
        wrap.innerHTML = `<p>Follow up or start new task <kbd>Ctrl N</kbd></p><button class="bcp-restart-btn">↺ Restart</button>`;
        msgs.appendChild(wrap);
        scrollToBottom();

        wrap.querySelector('.bcp-restart-btn').addEventListener('click', () => {
          step = 0;
          msgs.innerHTML = '';
          if (mdPanel) mdPanel.classList.add('hidden');
          expTree && expTree.querySelectorAll('.bcp-exp-file').forEach(f => f.remove());
          activateChat();
          updateUI();
        });
      }
    }

    async function advance() {
      if (busy || step >= SCRIPT.length) return;
      busy = true;

      sendBtn.disabled = true;
      sendBtn.classList.remove('pulse');
      inputBox.classList.remove('active');

      activateChat();

      const cur = SCRIPT[step];
      addUserMsg(cur.user);
      inputEl.textContent = '';
      inputEl.classList.remove('ready');

      await new Promise(r => setTimeout(r, 600));
      await renderSegments(cur.bob);

      step++;
      busy = false;
      updateUI();
    }

    sendBtn.addEventListener('click', advance);
    updateUI();
  }

})();
